version: "3.8"
services:
  ide:
    build:
      context: https://github.com/Redstoneguy129/Dev-Environment.git
      dockerfile: IDE.Dockerfile
    ports:
      - "2200:22"
    volumes:
      - "/home/cameron/projects:/home/cameron/projects"
    restart: unless-stopped
  share:
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    environment:
      - SHARE=Projects;/mnt/projects;yes;no;yes
    volumes:
      - "/home/cameron/projects:/mnt/projects"
  files:
    image: filebrowser/filebrowser
    ports:
      - "2202:80"
    volumes:
      - "/home/cameron/projects:/srv/projects"
      - "/home/cameron/vpn:/srv/vpn"
    restart: unless-stopped
